(DOCSP-21746) Add Scala examples to Structured Streaming page
mongodb/docs-spark-connector pull request #122
Opened 2022-04-07 19:05 UTC by zach-carr

## Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-spark-connector/blob/master/REVIEWING.md)

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-21746

### Snooty build log:

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21746/structured-streaming/

### Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Does it render on staging correctly?
- [ ] Are all the links working?
- [ ] Are the staging and workerpool job links in the PR description updated?

### If your page documents a concept, does it meet the following criteria?

- [ ] Target the [Jasmin persona](https://drive.google.com/file/d/14FbBOLCVxwSP6M9BK4Nz1Ir9tzxT8_02/view)
- [ ] Target the [Lucas persona](https://drive.google.com/file/d/1J2vqJxo7ldv7OP_obA9Q-avf0o_ju4Lk/view)

2022-04-29 15:36 UTC, zach-carr commented
Hey @rozza, the Scala examples are ready for a look whenever you get a chance. Thanks!

2022-04-29 15:53 UTC, rozza requested changes
Just some minor nits

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            streamingDataFrame = <local SparkSession>.readStream
Update `streamingDataFrame =` to `val streamingDataFrame =`

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            query = streamingDataFrame.writeStream
`val query =`

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            spark = SparkSession
`val spark = `

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            query = spark.readStream
`val query = `

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +              # manipulate your streaming data
Change to `// manipulate your streaming data`

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            spark = SparkSession
`val spark`

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            readSchema = StructType()
`val readSchema = `

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +            query = spark.readStream
`val query = `

2022-04-29 15:53 UTC, rozza commented on source/structured-streaming.txt
> +              # manipulate your streaming data
`// manipulate your streaming data`

2022-04-29 19:38 UTC, zach-carr commented
Ah my bad 🤦 I had those changes added after testing, just not committed and pushed (the `val`s anyway, didn't catch the comments)

Thanks!

2022-05-03 15:18 UTC, rozza approved these changes
LGTM!

2022-05-03 16:16 UTC, terakilobyte approved these changes
lgtm

2022-05-03 16:38 UTC, merged