(DOCSP-18818) Improve documentation for unsupported types
mongodb/docs-spark-connector pull request #77
Opened 2021-11-30 18:23 UTC by zach-carr

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-18818

### Snooty build log:
**Paste your workerpool job link here**

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-18818/faq/#how-do-i-use-mongodb-bson-types-that-are-unsupported-in-spark-

### Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Does it render on staging correctly?
- [ ] Are all the links working?
- [ ] Are the staging and workerpool job links in the PR description updated?

2021-12-01 17:20 UTC, ccho-mongodb requested changes
I think the changes I'm requesting are small, but would be great to re-review since it's early on in your rotation on the team so I just want to make sure we're on the same wavelength.

To answer your questions:

> I haven't tested the examples - they are pulled from Ross's comments in https://jira.mongodb.org/browse/SPARK-132. Do we need to test all code examples or is a technical review to confirm acceptable?

We should make our best effort to test. In some cases, that might not be straightforward. In those cases in which we don't test, when seeking the external review, please mention that explicitly.

> Do we need examples in other languages, or to more clearly label the examples "Scala?"

That would be a good question for the external reviewer. I think in our previous Spark/Kafka sync meeting with Ross and Robert, we mentioned that we want to focus on supporting Python. However, I'm not sure this means that we should remove any material that references other languages.

2021-12-01 17:20 UTC, ccho-mongodb commented on source/faq.txt
> +  (e.g. ``ObjectId``). The MongoDB Spark Connector handles converting
This could probably be shorted to Spark Connector since you've introduced it using the full name earlier.

2021-12-01 17:20 UTC, ccho-mongodb commented on source/faq.txt
> +  with ``StructFields.objectId``.
I try to avoid "with" when there's a more specific preposition you can use. Here, I would use "by" because that narrows down how it could be read.

2021-12-02 15:56 UTC, zach-carr commented
Thanks @ccho-mongodb! I incorporated all your comments - they all makes sense to me. I'll try to test these examples today and ask about including other examples in tech review. 

Ready for another look whenever you have time.

2021-12-03 02:11 UTC, ccho-mongodb approved these changes
LGTM, just one comment.

2021-12-03 16:37 UTC, zach-carr commented
Hi @rozza, would you mind reviewing this new FAQ item for unsupported MongoDB BSON types whenever you get a chance?

I have two questions:
1. I haven't been able to get the examples I took from your [Jira comment](https://jira.mongodb.org/browse/SPARK-132?focusedCommentId=1887881&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1887881) to work and I'm not familiar enough with Scala to debug very well - "new ObjectId()" is throwing an error.
`error: not found: type ObjectId`
`val ds = spark.createDataset(Seq(MyData(fieldTypes.ObjectId(new ObjectId()), 99)))`
Do you know what I'm missing?

2. Do we need Python or other examples here as well? If not, should I clearly label this as a Scala example?

2021-12-13 16:19 UTC, rozza approved these changes
LGTM

2021-12-13 16:28 UTC, merged